name: Build Release ZIP

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get version from git tag
      id: vars
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Create ZIP archive with version in name
      run: |
        zip -r swrifts-compendium-browser-${VERSION}.zip .
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: swrifts-compendium-browser-${{ env.VERSION }}.zip
        path: swrifts-compendium-browser-${{ env.VERSION }}.zip

    - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: "Automated release for version ${{ github.ref_name }}."
          draft: false
          prerelease: false