name: Package and Release Module

on:
  push:
    branches: [main]
    tags: ['v*']

permissions:
  contents: write

jobs:
  zip-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from module.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' module.json)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Zip folder (except .git and .github)
        run: |
          zip -r module.zip . -x "*.git*" "*.github*"

      - name: Create GitHub Release (if tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: module.zip
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: "Automated release for version ${{ steps.get_version.outputs.version }}."

      - name: Upload ZIP as an artifact (always)
        uses: actions/upload-artifact@v4
        with:
          name: module
          path: module.zip
